<a href="https://colab.research.google.com/github/irine002/Cleaned-Employee-Dataset/blob/main/Cleaned_Employee_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

df = pd.read_csv(r"/content/Day11_Messy_Company_Employee_Dataset.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (157, 12)

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [5]:
#Inspect the dataset

print("Dataset Information:")
df.info()

print("\nStatistical Summary:")
display(df.describe(include="all"))

print("\nColumn Names:")
print(df.columns.tolist())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

Statistical Summary:

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
count,157,157,152,157,153.000000,152,152.000000,154.000000,157,152,154.000000,155
unique,150,130,10,23,NaN,5,NaN,NaN,147,13,NaN,5
top,EMP0075,Nikhil Das,Marketing,Data Scientist,NaN,Male,NaN,NaN,2025-08-17,Chandigarh,NaN,Remote
freq,2,3,23,13,NaN,75,NaN,NaN,2,24,NaN,56
mean,NaN,NaN,NaN,NaN,38.130719,NaN,89240.592105,8.990909,NaN,NaN,3.525974,NaN
std,NaN,NaN,NaN,NaN,9.361661,NaN,22626.172309,4.983874,NaN,NaN,0.930233,NaN
min,NaN,NaN,NaN,NaN,21.000000,NaN,43331.000000,0.600000,NaN,NaN,2.000000,NaN
25%,NaN,NaN,NaN,NaN,30.000000,NaN,71198.500000,4.450000,NaN,NaN,3.000000,NaN
50%,NaN,NaN,NaN,NaN,39.000000,NaN,90046.500000,9.350000,NaN,NaN,4.000000,NaN
75%,NaN,NaN,NaN,NaN,46.000000,NaN,107328.000000,13.200000,NaN,NaN,4.000000,NaN
max,NaN,NaN,NaN,NaN,52.000000,NaN,162942.000000,17.400000,NaN,NaN,5.000000,NaN

Column Names:
['Employee_ID', 'Employee_Name', 'Department', 'Job_Title', 'Age', 'Gender', 'Annual_Salary', 'Experience_Years', 'Joining_Date', 'City', 'Performance_Score', 'Work_Mode']

In [6]:
#Check missing values
missing_values = df.isnull().sum()


print("Missing values in each column:")
print(missing_values)


print("\nTotal missing values:", df.isnull().sum().sum())

Missing values in each column:
Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

Total missing values: 32

In [7]:
#Check duplicate records
print("Number of duplicate rows:", df.duplicated().sum())
print("\nDuplicate records:")
display(df[df.duplicated(keep=False)])

Number of duplicate rows: 7

Duplicate records:

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
11,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
25,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
55,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
61,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
70,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
78,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
85,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
92,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote
100,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
104,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
110,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
112,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
139,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

In [8]:
#Check inconsistent categorical values
categorical_columns = [
    "Department",
    "Gender",
    "City",
    "Work_Mode"
]


for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False))

Department:
Department
Marketing           23
Engineering         21
Customer Success    20
Finance             19
Sales               19
Operations          17
Human Resources     16
Data & Analytics    15
NaN                  5
ENGINEERING          1
engineering          1
Name: count, dtype: int64

Gender:
Gender
Male      75
Female    68
Other      7
NaN        5
female     1
MALE       1
Name: count, dtype: int64

City:
City
Chandigarh    24
Pune          23
Jaipur        18
Mumbai        15
Hyderabad     14
Srinagar      13
Bengaluru     12
Delhi         11
Chennai       10
Kolkata        9
NaN            5
delhi          1
DELHI          1
Delhi          1
Name: count, dtype: int64

Work_Mode:
Work_Mode
Remote    56
Hybrid    50
Office    47
NaN        2
REMOTE     1
remote     1
Name: count, dtype: int64

In [9]:
#Remove duplicate records
df = df.drop_duplicates()


print("Shape after removing duplicates:", df.shape)
print("Remaining duplicates:", df.duplicated().sum())

Shape after removing duplicates: (150, 12)
Remaining duplicates: 0

In [10]:
#Standardize inconsistent categorical values
df["Department"] = df["Department"].astype("string").str.strip().str.title()
df["Gender"] = df["Gender"].astype("string").str.strip().str.title()
df["City"] = df["City"].astype("string").str.strip().str.title()
df["Work_Mode"] = df["Work_Mode"].astype("string").str.strip().str.title()
for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False))

Department:
Department
Engineering         23
Marketing           22
Customer Success    20
Sales               18
Human Resources     16
Operations          16
Data & Analytics    15
Finance             15
<NA>                 5
Name: count, dtype: Int64

Gender:
Gender
Male      72
Female    66
Other      7
<NA>       5
Name: count, dtype: Int64

City:
City
Pune          23
Chandigarh    22
Jaipur        17
Hyderabad     14
Delhi         14
Srinagar      13
Mumbai        13
Bengaluru     11
Chennai        9
Kolkata        9
<NA>           5
Name: count, dtype: Int64

Work_Mode:
Work_Mode
Remote    56
Hybrid    48
Office    44
<NA>       2
Name: count, dtype: Int64

In [11]:
#Correct data types
df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    errors="coerce"
)

#Convert numerical columns:

numeric_columns = [
    "Age",
    "Annual_Salary",
    "Experience_Years",
    "Performance_Score"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df.dtypes)

Employee_ID                  object
Employee_Name                object
Department           string[python]
Job_Title                    object
Age                         float64
Gender               string[python]
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                 string[python]
Performance_Score           float64
Work_Mode            string[python]
dtype: object

In [12]:
#Fill missing numerical values
numerical_missing_columns = [
    "Age",
    "Annual_Salary",
    "Experience_Years",
    "Performance_Score"
]
for col in numerical_missing_columns:
    df[col] = df[col].fillna(df[col].median())

In [13]:
print(df[numerical_missing_columns].isnull().sum())

Age                  0
Annual_Salary        0
Experience_Years     0
Performance_Score    0
dtype: int64

In [14]:
#fill missing categorical values
categorical_missing_columns = [
    "Department",
    "Gender",
    "City",
    "Work_Mode"
]

for col in categorical_missing_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

print(df[categorical_missing_columns].isnull().sum())

Department    0
Gender        0
City          0
Work_Mode     0
dtype: int64

In [15]:
#Handle essential columns
df = df.dropna(
    subset=["Employee_ID", "Employee_Name", "Job_Title"]
)

In [16]:
#Verify the cleaned dataset
print("Final Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)


display(df.head())

Final Dataset Shape: (150, 12)

Missing Values:
Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

Duplicate Rows: 0

Data Types:
Employee_ID                  object
Employee_Name                object
Department           string[python]
Job_Title                    object
Age                         float64
Gender               string[python]
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                 string[python]
Performance_Score           float64
Work_Mode            string[python]
dtype: object

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.2,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [19]:
#Compare before and after cleaning

# Original dataset statistics
original_df = pd.read_csv(r"/content/Day11_Messy_Company_Employee_Dataset.csv")


before_rows = original_df.shape[0]
before_columns = original_df.shape[1]
before_missing = original_df.isnull().sum().sum()
before_duplicates = original_df.duplicated().sum()


after_rows = df.shape[0]
after_columns = df.shape[1]
after_missing = df.isnull().sum().sum()
after_duplicates = df.duplicated().sum()


comparison = pd.DataFrame({
    "Condition": ["Before Cleaning", "After Cleaning"],
    "Rows": [before_rows, after_rows],
    "Columns": [before_columns, after_columns],
    "Missing Values": [before_missing, after_missing],
    "Duplicate Rows": [before_duplicates, after_duplicates]
})
display(comparison)

         Condition  Rows  Columns  Missing Values  Duplicate Rows
0  Before Cleaning   157       12              32               7
1   After Cleaning   150       12               0               0

In [20]:
#Export the cleaned dataset
output_file = "Cleaned_Company_Employee_Dataset.csv"
df.to_csv(output_file, index=False)
print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!

In [21]:
from google.colab import files

files.download("Cleaned_Company_Employee_Dataset.csv")